language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t ganiths/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true ganiths/react-test npm test -- --coverage
after_success:
    - docker build -t ganiths/multi-client ./client
    - docker build -t ganiths/multi-nginx ./nginx
    - docker build -t ganiths/multi-server ./server
    - docker build -t ganiths/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push ganiths/multi-client
    - docker push ganiths/multi-nginx
    - docker push ganiths/multi-server
    - docker push ganiths/multi-worker
deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-container
    env: MultiContainer-env
    bucket_name: elasticbeanstalk-us-east-2-374192245775
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
